runtime: python39

service: human

entrypoint: gunicorn -w 1 -b :$PORT main:app

instance_class: B4

env_variables:
  USER_GAE_PROJECT_ID: 1084173681698
  USER_TG_GROUP_ID: -1001515240020

basic_scaling:
  max_instances: 1
  idle_timeout: 5m
